services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: unless-stopped
    command: ["node", "build/server.js"]
